- name: Pull docker image of spe mini project
  hosts: local
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  tasks:
    - name: Pull spe mini image
      docker_image:
        name: gurleenk/spe_mini
        source: pull